---

- name: test if kibana_type is set correctly
  ansible.builtin.assert:
    that:
      - kibana_type is defined
      - kibana_type is string
      - kibana_type in [ "elastic", "oss" ]
    quiet: yes
